# Generated by Django 4.1.1 on 2022-09-26 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='description',
            new_name='element',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='completed',
            new_name='owned',
        ),
    ]
