# Generated by Django 4.1.1 on 2022-09-26 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0006_rename_id_pokemon_pokemonid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='pokemonId',
            new_name='id',
        ),
    ]
